name: Update Content Freshness Timestamps

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.html'
      - '**.css'
      - '**.js'
      - 'images/**'

jobs:
  update-timestamps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Updated to Node.js 18
          
      - name: Initialize npm and install dependencies
        run: |
          npm init -y
          npm install cheerio fs-extra moment
          
      - name: Update timestamp metadata
        run: |
          # Get current timestamp in ISO format
          TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          SIMPLE_DATE=$(date -u +"%Y-%m-%d")
          
          # Update sitemap.xml
          if [ -f sitemap.xml ]; then
            sed -i "s|<lastmod>[^<]*</lastmod>|<lastmod>$SIMPLE_DATE</lastmod>|g" sitemap.xml
          else
            # Create sitemap if it doesn't exist
            echo '<?xml version="1.0" encoding="UTF-8"?>
            <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
              <url>
                <loc>https://xperio.travel/</loc>
                <lastmod>'$SIMPLE_DATE'</lastmod>
                <changefreq>weekly</changefreq>
                <priority>1.0</priority>
              </url>
            </urlset>' > sitemap.xml
          fi
          
          # Create a node script to update the og:updated_time in HTML files
          cat > update-html.js << 'EOF'
          const fs = require('fs-extra');
          const cheerio = require('cheerio');
          const moment = require('moment');
          
          const timestamp = moment().utc().format('YYYY-MM-DDTHH:mm:ss[Z]');
          
          // Process index.html and any other main HTML files
          const htmlFiles = ['index.html'];
          
          htmlFiles.forEach(file => {
            if (fs.existsSync(file)) {
              let html = fs.readFileSync(file, 'utf8');
              const $ = cheerio.load(html);
              
              // Update or add og:updated_time
              let metaTag = $('meta[property="og:updated_time"]');
              if (metaTag.length) {
                metaTag.attr('content', timestamp);
              } else {
                $('head').append(`<meta property="og:updated_time" content="${timestamp}" />`);
              }
              
              // Save the file
              fs.writeFileSync(file, $.html());
              console.log(`Updated ${file} with timestamp ${timestamp}`);
            }
          });
          EOF
          
          # Execute the script
          node update-html.js
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add sitemap.xml index.html
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update content freshness timestamps [skip ci]" && git push)